# Generated by Django 4.1.7 on 2023-03-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_rename_lesson_question_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examgrades',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
